#!/usr/bin/env bash
# Cambia la configuración de hosts evitando el error de Device busy

# 1. Copiamos el archivo hosts a un archivo temporal en tu home
cp /etc/hosts ~/hosts.new

# 2. Hacemos el cambio de IP en ese archivo temporal
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new

# 3. Sobrescribimos el archivo original con el contenido del nuevo
# Usamos 'cp -f' para forzar la copia del contenido
cp -f ~/hosts.new /etc/hosts

# 4. Agregamos la línea de Facebook al final
echo "8.8.8.8 facebook.com" >> /etc/hosts